trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    image: $(dockerid).azurecr.io/$(imageName)
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

#- script: |
#    docker login -u "$(acrusername)" -p "$(acrpassword)" $(dockerid).azurecr.io
#    docker push $(dockerid).azurecr.io/$(imageName)
#  displayName: 'API docker build'
